#!/usr/bin/env bash

VBoxManage controlvm "Master" poweroff --type headless 2>/dev/null
for i in {1..5}; do
  VBoxManage controlvm "worker$i" poweroff --type headless 2>/dev/null
done
echo "Machines are down..."
