#!/usr/bin/env bash
echo "Shutting down the cluster..."
echo "Shutting down the master node..."
prlctl stop "Master"
for i in {1..5}; do
  prlctl stop "worker$i" 2>/dev/null
  if [ $? -ne 0 ]; then
    break
  fi
  echo "Shutting down worker node $i..."
done
echo "K8s cluster is down..."
