#!/usr/bin/env bash

echo "Starting k82 cluster..."
prlctl start "Master" 2>/dev/null
for i in {1..5}; do
  prlctl start "worker$i" 2>/dev/null
done
echo "The actual boot up time can take a while...."
