#!/usr/bin/env bash

VBoxManage startvm "Master" --type headless 2>/dev/null
for i in {1..5}; do
  VBoxManage startvm "worker$i" --type headless 2>/dev/null
done
echo "The actual boot up time can take a while...."