#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Please provide a worker number."
    echo "e.g. worker 2"
    echo "using default 1 now"
fi

chmod 600 ./common/ssh/* 2>/dev/null
ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ./common/ssh/id_rsa vagrant@192.168.10.11${1:-1}
