Vagrant.configure("2") do |config|

  # Global stuff for all nodes...
  # source: https://devops.stackexchange.com/questions/1237/how-do-i-configure-ssh-keys-in-a-vagrant-multi-machine-setup
  config.vm.box_check_update = false
  # config.vm.box = "ubuntu/bionic64" # 18.04 LTS
#   config.vm.box = "ubuntu/focal64" # 20.04 LTS
  config.vm.box = "mpasternak/focal64-arm" # 20.04 LTS Apple M1 chipset
  # config.vm.box = "ubuntu/hirsute64" # 21.04
  config.vm.synced_folder "..", "/vagrant", disabled: false
  config.vm.provision "shell", path: "../common/motd.sh", privileged: true
  config.vm.provision "file", source: "../common/ssh", destination: "/home/vagrant/.ssh"
  config.vm.provision "file", source: "../common/bin", destination: "/home/vagrant/bin"
  config.vm.provision :shell do |s|
    ssh_pub_key = File.readlines("../common/ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      mkdir -p /root/.ssh
      chmod 600 /home/vagrant/.ssh/*
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      echo "export PATH=~/bin:$PATH" >>/home/vagrant/.profile
      echo "alias k='kubectl'" >>/home/vagrant/.profile
      echo "alias h='history'" >>/home/vagrant/.profile
      echo "source <(kubectl completion bash)" >>/home/vagrant/.profile
      echo "complete -F __start_kubectl k" >>/home/vagrant/.profile
      echo "export DR='--dry-run=client -o yaml'" >>/home/vagrant/.profile
      chmod 600 /home/vagrant/.ssh/*
      chmod +x /home/vagrant/bin/* 
      echo "set et sts=2 sw=2 ts=2" >/home/vagrant/.vimrc
    SHELL
  end

  # Master Node
  config.vm.define "master", primary: true do |master|
    master.vm.network "private_network", ip: "192.168.10.100"
    master.vm.hostname = "master"
    master.vm.boot_timeout = 90
    master.vm.provider "parallels" do |prl|
          prl.update_guest_tools = true
          prl.check_guest_tools = true
          prl.linked_clone = true
          prl.memory = "4096"
          prl.name = "Master"
          prl.cpus = 2
    end
    master.vm.provision "shell", inline: "cp -r /vagrant/common/root_master/* /"
    master.vm.provision "shell", path: "../common/logo.sh", privileged: true
    master.vm.provision "shell", path: "k8sMaster.sh", privileged: false
  end

  # Worker node(s)
  1.upto(2) do |i|  # change the upto number to the amount of workers you need/want
    config.vm.define "worker#{i}" do |workers|
      workers.vm.network "private_network", ip: "192.168.10.11#{i}"
      workers.vm.hostname = "worker#{i}"
      workers.vm.boot_timeout = 90
      workers.vm.provider "parallels" do |prl|
              prl.update_guest_tools = true
              prl.check_guest_tools = true
              prl.linked_clone = true
              prl.memory = "2048"
              prl.name = "worker#{i}"
              prl.cpus = 2
      end
      workers.vm.provision "shell", inline: "cp -r /vagrant/common/root_worker/* /"
      workers.vm.provision "shell", path: "../common/logo.sh", privileged: true
      workers.vm.provision "shell", path: "k8sWorker.sh", privileged: false
      workers.vm.provision "shell", path: "join.sh", privileged: false
    end
  end
end
