Vagrant.configure("2") do |config|

  # Global stuff for all nodes...
  # source: https://devops.stackexchange.com/questions/1237/how-do-i-configure-ssh-keys-in-a-vagrant-multi-machine-setup
  config.vm.box_check_update = true
  # config.vm.box = "ubuntu/bionic64" # 18.04 LTS
  config.vm.box = "ubuntu/focal64" # 20.04 LTS
  # config.vm.box = "ubuntu/hirsute64" # 21.04
  config.vm.synced_folder "..", "/vagrant", disabled: false
  config.vm.provision "shell", path: "common/motd.sh", privileged: true
  config.vm.provision "file", source: "common/ssh", destination: "/home/vagrant/.ssh"
  config.vm.provision "file", source: "common/bin", destination: "/home/vagrant/bin"
  config.vm.provision :shell do |s|
    ssh_pub_key = File.readlines("./ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      mkdir -p /root/.ssh
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      echo "export PATH=~/bin:$PATH" >>/home/vagrant/.profile
      chmod 600 /home/vagrant/.ssh/*
      chmod +x /home/vagrant/bin/* 
      echo "set et sts=2 sw=2 ts=2" >/home/vagrant/.vimrc
    SHELL
  end

  # Master Node
  config.vm.define "master", primary: true do |master|
    master.vm.network "private_network", ip: "192.168.10.100"
    master.vm.hostname = "master"
    master.vm.boot_timeout = 60
    master.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "4096"
      vb.name = "Master"
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--vram", "20"]
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
      vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
    end
    master.vm.provision "shell", inline: "cp -r /vagrant/root_master/* /"
    master.vm.provision "shell", path: "logo.sh", privileged: true
  end

  # Worker node(s)
  1.upto(1) do |i|  # change the upto number to the amount of workers you need/want
    config.vm.define "worker#{i}" do |workers|
      workers.vm.network "private_network", ip: "192.168.10.11#{i}"
      workers.vm.hostname = "worker#{i}"
      workers.vm.boot_timeout = 60
      workers.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "2048"
        vb.name = "worker#{i}"
        vb.cpus = 2
        vb.customize ["modifyvm", :id, "--vram", "20"]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
      end
      workers.vm.provision "shell", inline: "cp -r /vagrant/root_worker/* /"
      workers.vm.provision "shell", path: "logo.sh", privileged: true
    end
  end
end
