#!/bin/sh
cat <<EOT
     _    ___       __        __         _
    | | _( _ ) ___  \ \      / /__  _ __| | _____ _ __
    | |/ / _ \/ __|  \ \ /\ / / _ \| '__| |/ / _ \ '__|
    |   < (_) \__ \   \ V  V / (_) | |  |   <  __/ |
    |_|\_\___/|___/    \_/\_/ \___/|_|  |_|\_\___|_|

  Created by Ivo Woltring:
  * Blog    : https://www.ivonet.nl
  * Website : https://www.ivowoltring.com
  * Github  : https://github.com/ivonet
  * Docker  : https://hub.docker.com/u/ivonet
  * LinkedIn: https://www.linkedin.com/in/ivonet/
  * Twitter : @ivonet

EOT
